---

- hosts: webservers

  become: yes

  tasks:
  
  - name: Installing NGINX SERVERS ON devA devB and devC !!!!!

    apt:

      name: nginx

      state: present

      update_cache: true
    notify:

    - start nginx

  - name: INSTALLING PHP ON devA devB and devC !!!!!

    apt:

      name: php

      state: present

      update_cache: true



  - name: INSTALLING PHP-FPM  devA devB and devC !!!!!

    apt:

      name: php-fpm

      state: present

      update_cache: true

    notify:

    - start php7.4-fpm
    

  - name: RUNNING PHP FILES ON NGINX :- php7.4-fpm cgi.fix_pathinfo=0 
    lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
    - restart php7.4-fpm
    - restart nginx

  - name: REMOVING "nginx.conf" site at etc/nginx/
    file:
       path: "/etc/nginx/nginx.conf"
       state: absent
  
  - name: SETTING UP nginx.conf file at etc/nginx/
    template:
       src: "./default1"
       dest: "/etc/nginx/nginx.conf"
    notify:
    - restart php7.4-fpm
    - restart nginx



  - name: REMOVING DEFAULT at etc/nginx/sites-enabled
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent
    notify: 
    - restart nginx

  - name: SETTING UP NGINX CONF FILE at etc/nginx/sites-available
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: CHANGES etc/nginx/sites-available to etc/nginx/sites-enable !!!!
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link
    notify: 
    - restart nginx
   

  - name: ALLOWING CONNECTION FOR NGINX 
    ufw:
       rule: allow
       port: '80'
       proto: any


  - name: SETS UP index.PHP Page at root var/www/html
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"
    notify:
    - restart nginx
    - start nginx
    - restart php7.4-fpm
    - start php7.4-fpm 


  handlers:

  - name: STARTING php7.4-fpm
    service:

      name: php7.4-fpm

      state: started



  - name: start nginx
    service:

      name: nginx

      state: started


  - name: RESTARTING php7.4-fpm
    service:

      name: php7.4-fpm

      state: restarted
  - name: restart nginx

    service:

      name: nginx

      state: restarted
- hosts: haproxy
  become: yes

  tasks:
  


  - name: INSTALLING HAPROXY ON DEVHAPROXY !!!!!
    apt:
      name: haproxy
      state: present
      update_cache: true

  - name: HAPROXY WITH JINJA2 TEMPLATE file 
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0640
      owner: root
      group: root
    notify:
    - restart haproxy
    
  - name: SETTING DEFAULT FLAG TO 1 WHICH ENABLES HAPROXY 
    lineinfile:
      dest: /etc/default/haproxy
      regexp: "^ENABLED"
      line: "ENABLED=1"
    notify:
    - restart haproxy


  handlers:
  
  - name: RESTART HAPROXY
    service:
        name: haproxy
        state: restarted

   
...
